name: Code Quality
on:
  pull_request:
    branches: [develop]
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  test:
    name: Lint and test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed project files (lint)
        id: changed-project-lint
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.{js,ts,tsx}
            .github/workflows/test.yml
          files_ignore: |
            .eslintrc.js,
            jest.config.js,
            next.config.js,
            postcss.config.js,
            .prettierrc.js,
            tailwind.config.js

      - name: Get changed project files (test)
        id: changed-project-test
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.{js,ts,tsx}
            .github/workflows/test.yml
          files_ignore: |
            .eslintrc.js,
            postcss.config.js,
            tailwind.config.js

      - name: Get changed markdown files
        id: changed-markdown
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.md
            .github/workflows/test.yml

      - name: Setup Node JS
        if: steps.changed-project-test.outputs.any_modified == 'true' || steps.changed-project-lint.outputs.any_modified == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION || 'latest' }}
          cache: 'yarn'

      - name: Install dependencies
        if: steps.changed-project-test.outputs.any_modified == 'true' || steps.changed-project-lint.outputs.any_modified == 'true'
        run: |
          echo "::group::Node version"
          echo 'node version requested: ${{ vars.NODE_VERSION || 'latest' }}'
          echo 'node version: '$(node --version)
          echo "::endgroup::"

          version=$(yarn --version)
          requested_version=${{ vars.YARN_VERSION || 'latest' }}

          if [ version != requested_version ]
          then
            yarn set version ${requested_version}
          fi

          echo "::group::Yarn version"
          echo 'initial yarn version: '${version}
          echo 'yarn version requested: '${requested_version}
          echo 'yarn version: '$(yarn --version)
          echo "::endgroup::"

          yarn install --immutable

      - name: Lint all Documentation
        if: steps.changed-markdown.outputs.any_modified == 'true'
        uses: DavidAnson/markdownlint-cli2-action@v14
        with:
          globs: |
            **/*.md
            !**/node_modules/**

      - name: Lint project
        if: steps.changed-project-lint.outputs.any_modified == 'true'
        env:
          WP_DOMAIN: ${{ vars.WP_DOMAIN }}
          WP_API_URL: http://${{ vars.WP_DOMAIN }}
          GRAPHQL_URL: http://${{ vars.WP_DOMAIN }}/graphql
        run: yarn lint

      - name: Run Jest
        if: steps.changed-project-test.outputs.any_modified == 'true'
        env:
          WP_DOMAIN: ${{ vars.WP_DOMAIN }}
          WP_API_URL: http://${{ vars.WP_DOMAIN }}
          GRAPHQL_URL: http://${{ vars.WP_DOMAIN }}/graphql
        run: yarn test:unit

      # - name: Run Playwright tests
      #   if: steps.changed-project-test.outputs.any_modified == 'true'
      #   run: yarn test:e2e
